In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

import numpy as np 
import pandas as pd 
import pandas as pd 
import numpy as np 
import scipy as sp 
import sklearn
import random 
import time 

from sklearn import preprocessing, model_selection


from keras.models import Sequential 
from keras.layers import Dense 
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder
from keras.utils.np_utils import to_categorical
from sklearn.utils import shuffle




/Users/luca/anaconda3/envs/kerasenv/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [5]:
data = pd.read_csv('./data/wifi_values.csv')
data.mac = pd.factorize(df.mac)[0]

In [7]:
data = shuffle(data)


i = 8
data_to_predict = data[:i].reset_index(drop = True)
predict_room = data_to_predict.location 
predict_room = np.array(predict_room)
prediction = np.array(data_to_predict.drop(['location'],axis= 1))

data = data[i:].reset_index(drop = True)

In [8]:
X = data.drop(['location'], axis = 1)
X = np.array(X)
Y = data['location']

In [9]:
encoder = LabelEncoder()
encoder.fit(Y)
Y = encoder.transform(Y)
Y = np_utils.to_categorical(Y)
print(Y)

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 ...
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
train_x, test_x, train_y, test_y = model_selection.train_test_split(X,Y,test_size = 0.1, random_state = 0)

In [17]:
input_dim = len(data.columns) - 1

model = Sequential()
model.add(Dense(8, input_dim = input_dim , activation = 'relu'))
model.add(Dense(10, activation = 'relu'))
model.add(Dense(10, activation = 'relu'))
model.add(Dense(10, activation = 'relu'))
model.add(Dense(3, activation = 'softmax'))

model.compile(loss = 'categorical_crossentropy' , optimizer = 'adam' , metrics = ['accuracy'] )

model.fit(train_x, train_y, epochs = 100, batch_size = 2)

scores = model.evaluate(test_x, test_y)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

Epoch 1/100
343/343 [==============================] - 0s 1ms/step - loss: 0.9420 - acc: 0.6851
Epoch 2/100
343/343 [==============================] - 0s 627us/step - loss: 0.5456 - acc: 0.7464
Epoch 3/100
343/343 [==============================] - 0s 701us/step - loss: 0.5559 - acc: 0.7493
Epoch 4/100
343/343 [==============================] - 0s 682us/step - loss: 0.5276 - acc: 0.7493
Epoch 5/100
343/343 [==============================] - 0s 786us/step - loss: 0.5181 - acc: 0.7522
Epoch 6/100
343/343 [==============================] - 0s 812us/step - loss: 0.5013 - acc: 0.7755
Epoch 7/100
343/343 [==============================] - 0s 796us/step - loss: 0.5046 - acc: 0.7697
Epoch 8/100
343/343 [==============================] - 0s 820us/step - loss: 0.4851 - acc: 0.7813
Epoch 9/100
343/343 [==============================] - 0s 689us/step - loss: 0.5076 - acc: 0.7638
Epoch 10/100
343/343 [==============================] - 0s 690us/step - loss: 0.4800 - acc: 0.7872
Epoch 11/100
343/343 

343/343 [==============================] - 0s 664us/step - loss: 0.1401 - acc: 0.9504
Epoch 84/100
343/343 [==============================] - 0s 557us/step - loss: 0.1304 - acc: 0.9563
Epoch 85/100
343/343 [==============================] - 0s 563us/step - loss: 0.1236 - acc: 0.9534
Epoch 86/100
343/343 [==============================] - 0s 568us/step - loss: 0.1369 - acc: 0.9563
Epoch 87/100
343/343 [==============================] - 0s 562us/step - loss: 0.1258 - acc: 0.9504
Epoch 88/100
343/343 [==============================] - 0s 564us/step - loss: 0.1264 - acc: 0.9563
Epoch 89/100
343/343 [==============================] - 0s 578us/step - loss: 0.1222 - acc: 0.9621
Epoch 90/100
343/343 [==============================] - 0s 553us/step - loss: 0.1151 - acc: 0.9679
Epoch 91/100
343/343 [==============================] - 0s 574us/step - loss: 0.1259 - acc: 0.9563
Epoch 92/100
343/343 [==============================] - 0s 567us/step - loss: 0.1222 - acc: 0.9679
Epoch 93/100
343/343 [=

In [16]:
predictions = model.predict_classes(prediction)
prediction_ = np.argmax(to_categorical(predictions), axis = 1)
prediction_ = encoder.inverse_transform(prediction_)

for i, j in zip(prediction_ , predict_room):
    print( " the nn predict {}, and the room to find is {}".format(i,j))

 the nn predict Bedroom, and the room to find is Bedroom
 the nn predict Living, and the room to find is Kitchen
 the nn predict Living, and the room to find is Living
 the nn predict Kitchen, and the room to find is Kitchen
 the nn predict Bedroom, and the room to find is Bedroom
 the nn predict Kitchen, and the room to find is Kitchen
 the nn predict Living, and the room to find is Living
 the nn predict Living, and the room to find is Living


/Users/luca/anaconda3/envs/kerasenv/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [23]:
model.predict_classes(prediction)

array([0, 2, 2, 1, 0, 1, 2, 2])

In [24]:
prediction

array([[ 42, -54,   1],
       [ 44, -52,   0],
       [ 45, -51,   0],
       [ 39, -57,   0],
       [ 41, -55,   1],
       [ 39, -57,   0],
       [ 48, -48,   0],
       [ 44, -52,   0]])

In [61]:
test = np.array([[43,-53,1]])

In [62]:
pred = model.predict_classes(test)

In [63]:
prediction_ = np.argmax(to_categorical(pred), axis = 1)
prediction_ = encoder.inverse_transform(prediction_)

/Users/luca/anaconda3/envs/kerasenv/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [64]:
prediction_

array(['Bedroom'], dtype=object)

In [65]:
def save_model(model):
    # saving model
    json_model = model.to_json()
    open('model_architecture.json', 'w').write(json_model)
    # saving weights
    model.save_weights('model_weights.h5', overwrite=True)

In [66]:
save_model(model)

In [67]:
from keras import backend as K
import tensorflow as tf

def freeze_session(session, keep_var_names=None, output_names=None, clear_devices=True):
    """
    Freezes the state of a session into a pruned computation graph.

    Creates a new computation graph where variable nodes are replaced by
    constants taking their current value in the session. The new graph will be
    pruned so subgraphs that are not necessary to compute the requested
    outputs are removed.
    @param session The TensorFlow session to be frozen.
    @param keep_var_names A list of variable names that should not be frozen,
                          or None to freeze all the variables in the graph.
    @param output_names Names of the relevant graph outputs.
    @param clear_devices Remove the device directives from the graph for better portability.
    @return The frozen graph definition.
    """
    from tensorflow.python.framework.graph_util import convert_variables_to_constants
    graph = session.graph
    with graph.as_default():
        freeze_var_names = list(set(v.op.name for v in tf.global_variables()).difference(keep_var_names or []))
        output_names = output_names or []
        output_names += [v.op.name for v in tf.global_variables()]
        # Graph -> GraphDef ProtoBuf
        input_graph_def = graph.as_graph_def()
        if clear_devices:
            for node in input_graph_def.node:
                node.device = ""
        frozen_graph = convert_variables_to_constants(session, input_graph_def,
                                                      output_names, freeze_var_names)
        return frozen_graph


frozen_graph = freeze_session(K.get_session(),
                              output_names=[out.op.name for out in model.outputs])

INFO:tensorflow:Froze 105 variables.
Converted 105 variables to const ops.


In [68]:
tf.train.write_graph(frozen_graph, "model", "tf_model.pb", as_text=False)

'model/tf_model.pb'