In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

import numpy as np 
import pandas as pd 
import pandas as pd 
import numpy as np 
import scipy as sp 
import sklearn
import random 
import time 

from sklearn import preprocessing, model_selection


from keras.models import Sequential 
from keras.layers import Dense 
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder
from keras.utils.np_utils import to_categorical
from sklearn.utils import shuffle




/Users/luca/anaconda3/envs/kerasenv/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
data = pd.read_csv('./data/wifi_values.csv')
data.mac = pd.factorize(data.mac)[0]

In [3]:
data = shuffle(data)


i = 8
data_to_predict = data[:i].reset_index(drop = True)
predict_room = data_to_predict.location 
predict_room = np.array(predict_room)
prediction = np.array(data_to_predict.drop(['location'],axis= 1))

data = data[i:].reset_index(drop = True)

In [4]:
X = data.drop(['location'], axis = 1)
X = np.array(X)
Y = data['location']

In [5]:
encoder = LabelEncoder()
encoder.fit(Y)
Y = encoder.transform(Y)
Y = np_utils.to_categorical(Y)
print(Y)

[[0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 ...
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]


In [6]:
train_x, test_x, train_y, test_y = model_selection.train_test_split(X,Y,test_size = 0.1, random_state = 0)

In [7]:
input_dim = len(data.columns) - 1

model = Sequential()
model.add(Dense(8, input_dim = input_dim , activation = 'relu'))
model.add(Dense(10, activation = 'relu'))
model.add(Dense(10, activation = 'relu'))
# model.add(Dense(10, activation = 'relu'))
model.add(Dense(4, activation = 'softmax'))

model.compile(loss = 'categorical_crossentropy' , optimizer = 'adam' , metrics = ['accuracy'] )

model.fit(train_x, train_y, epochs = 100, batch_size = 5)

scores = model.evaluate(test_x, test_y)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

Epoch 1/100
913/913 [==============================] - 0s 423us/step - loss: 3.6097 - acc: 0.4173
Epoch 2/100
913/913 [==============================] - 0s 231us/step - loss: 1.0142 - acc: 0.5674
Epoch 3/100
913/913 [==============================] - 0s 268us/step - loss: 0.8647 - acc: 0.6112
Epoch 4/100
913/913 [==============================] - 0s 217us/step - loss: 0.7661 - acc: 0.6758
Epoch 5/100
913/913 [==============================] - 0s 215us/step - loss: 0.6911 - acc: 0.7437
Epoch 6/100
913/913 [==============================] - 0s 210us/step - loss: 0.6425 - acc: 0.7634
Epoch 7/100
913/913 [==============================] - 0s 256us/step - loss: 0.5943 - acc: 0.7853
Epoch 8/100
913/913 [==============================] - 0s 229us/step - loss: 0.5489 - acc: 0.7886
Epoch 9/100
913/913 [==============================] - 0s 249us/step - loss: 0.5094 - acc: 0.8028
Epoch 10/100
913/913 [==============================] - 0s 246us/step - loss: 0.4859 - acc: 0.8061
Epoch 11/100
913/91

913/913 [==============================] - 0s 223us/step - loss: 0.3761 - acc: 0.8269
Epoch 84/100
913/913 [==============================] - 0s 205us/step - loss: 0.3837 - acc: 0.8269
Epoch 85/100
913/913 [==============================] - 0s 218us/step - loss: 0.3754 - acc: 0.8237
Epoch 86/100
913/913 [==============================] - 0s 200us/step - loss: 0.3804 - acc: 0.8226
Epoch 87/100
913/913 [==============================] - 0s 202us/step - loss: 0.3801 - acc: 0.8226
Epoch 88/100
913/913 [==============================] - 0s 203us/step - loss: 0.3799 - acc: 0.8258
Epoch 89/100
913/913 [==============================] - 0s 197us/step - loss: 0.3747 - acc: 0.8237
Epoch 90/100
913/913 [==============================] - 0s 205us/step - loss: 0.3764 - acc: 0.8280
Epoch 91/100
913/913 [==============================] - 0s 205us/step - loss: 0.3915 - acc: 0.8072
Epoch 92/100
913/913 [==============================] - 0s 236us/step - loss: 0.3773 - acc: 0.8193
Epoch 93/100
913/913 [=

In [8]:
predictions = model.predict_classes(prediction)
prediction_ = np.argmax(to_categorical(predictions), axis = 1)
prediction_ = encoder.inverse_transform(prediction_)

for i, j in zip(prediction_ , predict_room):
    print( " the nn predict {}, and the room to find is {}".format(i,j))

 the nn predict Living, and the room to find is Living
 the nn predict Bedroom, and the room to find is Bedroom
 the nn predict Living, and the room to find is Living
 the nn predict Bedroom, and the room to find is Bedroom
 the nn predict Kitchen, and the room to find is Kitchen
 the nn predict Living, and the room to find is Living
 the nn predict Office, and the room to find is Bedroom
 the nn predict Living, and the room to find is Living


/Users/luca/anaconda3/envs/kerasenv/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [9]:
model.predict_classes(prediction)

array([2, 0, 2, 0, 1, 2, 3, 2])

In [10]:
prediction

array([[ 44, -52,   1],
       [ 35, -61,   0],
       [ 44, -52,   1],
       [ 39, -57,   0],
       [ 35, -61,   1],
       [ 50, -46,   1],
       [ 28, -68,   0],
       [ 44, -52,   1]])

In [11]:
test = np.array([[43,-53,1]])

In [12]:
pred = model.predict_classes(test)

In [13]:
prediction_ = np.argmax(to_categorical(pred), axis = 1)
prediction_ = encoder.inverse_transform(prediction_)

/Users/luca/anaconda3/envs/kerasenv/lib/python3.6/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [14]:
prediction_

array(['Living'], dtype=object)

In [15]:
def save_model(model):
    # saving model
    json_model = model.to_json()
    open('model_architecture.json', 'w').write(json_model)
    # saving weights
    model.save_weights('model_weights.h5', overwrite=True)

In [20]:
# save_model(model)

In [17]:
from keras import backend as K
import tensorflow as tf

def freeze_session(session, keep_var_names=None, output_names=None, clear_devices=True):
    """
    Freezes the state of a session into a pruned computation graph.

    Creates a new computation graph where variable nodes are replaced by
    constants taking their current value in the session. The new graph will be
    pruned so subgraphs that are not necessary to compute the requested
    outputs are removed.
    @param session The TensorFlow session to be frozen.
    @param keep_var_names A list of variable names that should not be frozen,
                          or None to freeze all the variables in the graph.
    @param output_names Names of the relevant graph outputs.
    @param clear_devices Remove the device directives from the graph for better portability.
    @return The frozen graph definition.
    """
    from tensorflow.python.framework.graph_util import convert_variables_to_constants
    graph = session.graph
    with graph.as_default():
        freeze_var_names = list(set(v.op.name for v in tf.global_variables()).difference(keep_var_names or []))
        output_names = output_names or []
        output_names += [v.op.name for v in tf.global_variables()]
        # Graph -> GraphDef ProtoBuf
        input_graph_def = graph.as_graph_def()
        if clear_devices:
            for node in input_graph_def.node:
                node.device = ""
        frozen_graph = convert_variables_to_constants(session, input_graph_def,
                                                      output_names, freeze_var_names)
        return frozen_graph


frozen_graph = freeze_session(K.get_session(),
                              output_names=[out.op.name for out in model.outputs])

INFO:tensorflow:Froze 37 variables.
Converted 37 variables to const ops.


In [19]:
# tf.train.write_graph(frozen_graph, "model", "tf_model.pb", as_text=False)

'model/tf_model.pb'